ci: docker metadata

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -41,7 +41,52 @@ jobs:
       # max-parallel: 1
       matrix:
         release-pr: ${{ fromJson(needs.releases-metadata.outputs.pending_releases) }}
+    permissions: 
+      contents: read
+      packages: write
     steps:
-      - name: Print
+      - name: Release metadata
+        id: metadata
         run: |
-          echo "matrix value: ${{ toJson(matrix.release-pr) }}"
+          set -Eeuo pipefail
+          pr_number="${{ toJson(matrix.release-pr) }}" | jq -r .number
+          pr_info=$(gh pr view $pr_number --json title,labels,mergeCommit,state,number,body | jq 'select(.state=="MERGED" and (.labels[] | .name=="release: pending"))')
+          [[ -z "$pr_info" ]] && { echo "Pull request $pr_number has invalid release state"; exit 1; }
+
+          commit=$(echo $pr_info | jq -r .mergeCommit.oid)
+          version=$(git show "$commit":charts/learnrelease/Chart.yaml | yq .version)
+          version=${version#v}
+          tag=v${version}
+          release_body=$(echo $pr_info | jq -r .body)
+
+          echo "commit=$commit" >>"$GITHUB_OUTPUT"
+          echo "version=$version" >>"$GITHUB_OUTPUT"
+          echo "tag=$tag" >>"$GITHUB_OUTPUT"
+          echo "release_body=$release_body" >>"$GITHUB_OUTPUT"
+      - name: Print metadata
+        run: |
+          echo "commit: ${{ steps.metadata.outputs.commit }}"
+          echo "version: ${{ steps.metadata.outputs.version }}"
+          echo "tag: ${{ steps.metadata.outputs.tag }}"
+          echo "release_body: ${{ steps.metadata.outputs.release_body }}"
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ steps.metadata.outputs.commit }}
+      - uses: docker/login-action@v3
+        with:
+          registry: ghcr.io
+          username: ${{ github.actor }}
+          password: ${{ secrets.GITHUB_TOKEN }}
+      - uses: docker/setup-buildx-action@v3
+      - name: Container metadata
+        id: container-metadata
+        uses: docker/metadata-action@v5
+        with:
+          images: "${{ github.repository }}/learnrelease"
+          tags: ${{ steps.metadata.outputs.version }}
+      - name: Print container metadata
+        run: |
+          echo "tags: ${{ steps.container-metadata.outputs.tags }}"
+          echo "labels: ${{ steps.container-metadata.outputs.labels }}"
+
+      
