ci: add safeguard to release template workflow

diff --git a/.github/workflows/template-release-pr.yml b/.github/workflows/template-release-pr.yml
--- a/.github/workflows/template-release-pr.yml
+++ b/.github/workflows/template-release-pr.yml
@@ -55,8 +55,14 @@ jobs:
           [[ -z "$pr_info" ]] && { echo "Pull request $pr_number has invalid release state"; exit 1; }
 
           commit=$(echo $pr_info | jq -r .mergeCommit.oid)
-          version=$(git show "$commit":"${{ inputs.version-file-path }}" | yq .version)
-          version=${version#v}
+          version=$(git show "$commit":"${{ inputs.version-file-path }}")
+
+          # Check that extracted version is valid semver
+          if [[ ! "$new_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.-]+)?(\+[0-9A-Za-z.-]+)?$ ]]; then
+            echo "Invalid version format. Use full semver: X.Y.Z, X.Y.Z-alpha, etc."
+            exit 1
+          fi
+
           tag=v${version}
           is_prerelease="false"
           if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+- ]]; then
