ci: uncomment metadata script

diff --git a/.github/workflows/template-release-pr.yml b/.github/workflows/template-release-pr.yml
--- a/.github/workflows/template-release-pr.yml
+++ b/.github/workflows/template-release-pr.yml
@@ -42,23 +42,22 @@ jobs:
         run: |
           set -Eeuo pipefail
           pr_number=${{ inputs.pull_request_number }}
-          echo "pr number: $pr_number"
-          # pr_info=$(gh pr view $pr_number --json title,labels,mergeCommit,state,number | jq 'select(.state=="MERGED" and (.labels[] | .name=="release: pending"))')
-          # [[ -z "$pr_info" ]] && { echo "Pull request $pr_number has invalid release state"; exit 1; }
+          pr_info=$(gh pr view $pr_number --json title,labels,mergeCommit,state,number | jq 'select(.state=="MERGED" and (.labels[] | .name=="release: pending"))')
+          [[ -z "$pr_info" ]] && { echo "Pull request $pr_number has invalid release state"; exit 1; }
 
-          # commit=$(echo $pr_info | jq -r .mergeCommit.oid)
-          # version=$(git show "$commit":charts/learnrelease/Chart.yaml | yq .version)
-          # version=${version#v}
-          # tag=v${version}
-          # is_prerelease="false"
-          # if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+- ]]; then
-          #     is_prerelease="true"
-          # fi
+          commit=$(echo $pr_info | jq -r .mergeCommit.oid)
+          version=$(git show "$commit":charts/learnrelease/Chart.yaml | yq .version)
+          version=${version#v}
+          tag=v${version}
+          is_prerelease="false"
+          if [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+- ]]; then
+              is_prerelease="true"
+          fi
 
-          # echo "commit=$commit" >>"$GITHUB_OUTPUT"
-          # echo "version=$version" >>"$GITHUB_OUTPUT"
-          # echo "tag=$tag" >>"$GITHUB_OUTPUT"
-          # echo "is_prerelease=$is_prerelease" >>"$GITHUB_OUTPUT"
+          echo "commit=$commit" >>"$GITHUB_OUTPUT"
+          echo "version=$version" >>"$GITHUB_OUTPUT"
+          echo "tag=$tag" >>"$GITHUB_OUTPUT"
+          echo "is_prerelease=$is_prerelease" >>"$GITHUB_OUTPUT"
       - name: Print release metadata
         run: |
           echo "commit: ${{ steps.metadata.outputs.commit }}"
